# Default values for wisp-gateway.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: competemcgill/wisp-gateway
  tag: "latest"
  pullPolicy: Always

nameOverride: ""
fullnameOverride: "wisp-gateway"

service:
  type: LoadBalancer
  httpPort: 80
  httpsPort: 443
  loadBalancerIP: ""

ingress:
  enabled: false

resources:
  limits:
    cpu: 50m
    memory: 50Mi
  requests:
    cpu: 50m
    memory: 50Mi
