apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "wisp-gateway.fullname" . }}
  labels:
    {{- include "wisp-gateway.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "wisp-gateway.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "wisp-gateway.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
            - name: https
              containerPort: 443
              protocol: TCP
          volumeMounts:
            - name: tls
              mountPath: "/tls"
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: "tls"
          secret:
            secretName: "domain-secrets"
