apiVersion: v1
kind: Service
metadata:
  name: {{ include "wisp-gateway.fullname" . }}
  labels:
    {{- include "wisp-gateway.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  ports:
    - port: {{ .Values.service.httpPort }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.service.httpsPort }}
      targetPort: https
      protocol: TCP
      name: https
  selector:
    {{- include "wisp-gateway.selectorLabels" . | nindent 4 }}
